### PR TITLE
(GH-69) Add LastChangedRevision property to SvnInfo

### LINKED ISSUE #69: SvnInfo doesn't have LastChangedRevision attribute
Hi,

I'd like to access Last Changed Revision but this addin only supports the "Revision" field.

Example from running svn info in the command line:

```
C:\svn\branch>svn info
Path: .
Working Copy Root Path: C:\svn\branch
(...)
Revision: 222416
(...)
Last Changed Rev: 222214
```

Last changed revision cannot be accessed from this addin.

### PR DESCRIPTION
**Pull request by Diogomrol**
Implemented the support for the property LastChangedRevision and a corresponding test.

Fixes #69

### CODE REVIEW

**Comment by pascalberger** [comment]
@Diogomrol Don't care about the failing build, it is not caused by your changes. I'll try to fix it later today and rebase your branch on it.

**Comment by Diogomrol** [comment]
@pascalberger though so, thank you :)

**Comment by pascalberger** [comment]
@Diogomrol This repo follows [GitFlow](https://nvie.com/posts/a-successful-git-branching-model/) and active development is don on the `develop` branch. I can rebase your `master` branch so that we can proceed with this PR, but then the `master` branch in your fork would be out of sync with `master` branch of the original repo (you may want to delete and fork the repo again for future changes). Should I proceed like this or do you prefer to make the changes on a feature branch and submit a new PR?

**Comment by Diogomrol** [comment]
@pascalberger I will close this PR and open a new one then :) Thank you!

**Pull request closed without merging**
